# Generated by Django 3.2.6 on 2021-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_caption', models.CharField(max_length=100)),
                ('image_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_text', models.TextField()),
                ('blog_date_added', models.DateTimeField(auto_now_add=True)),
                ('blog_date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('blog_images', models.ManyToManyField(to='Blog.BlogImagesModel')),
                ('blog_tag', models.ManyToManyField(related_name='tags', to='Blog.TagsModel')),
            ],
        ),
    ]
