# Generated by Django 3.2.6 on 2021-08-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogimagesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagesmodel',
            name='image_caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogimagesmodel',
            name='image_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
