# Generated by Django 3.2.6 on 2021-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210823_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagesmodel',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
    ]
