# Generated by Django 3.2.6 on 2021-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_repository', models.URLField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('project_description', models.TextField()),
                ('project_demonstration', models.TextField(blank=True, null=True)),
                ('project_thumbnail', models.ImageField(upload_to='project_thumbnail')),
                ('slug', models.SlugField()),
                ('project_tech', models.ManyToManyField(to='Project.TechModel')),
            ],
        ),
    ]
