# Generated by Django 3.2.6 on 2021-09-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_projectmodel_project_screencapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_brief',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
